name: bseymour
favicon: null
layout_spectrum: 0.7862250353209674
typography_spectrum: 0.9167064786888659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7424545052926987
  lightness: 0.34839574131183326
  saturation: 0.5753055484965444
  rhythmicContrast: 0.46551082050427794
purpose: []
